<?php

require_once JPATH_PLATFORM.'/joomla/installer/adapters/file.php';

/**
 * Test class for JInstallerFile.
 * Generated by PHPUnit on 2012-02-29 at 17:41:34.
 */
class JInstallerFileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JInstallerFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JInstallerFile;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JInstallerFile::loadLanguage
     * @todo Implement testLoadLanguage().
     */
    public function testLoadLanguage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerFile::install
     * @todo Implement testInstall().
     */
    public function testInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerFile::update
     * @todo Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerFile::uninstall
     * @todo Implement testUninstall().
     */
    public function testUninstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerFile::refreshManifestCache
     * @todo Implement testRefreshManifestCache().
     */
    public function testRefreshManifestCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
