<?php

require_once JPATH_PLATFORM.'/joomla/installer/adapters/language.php';

/**
 * Test class for JInstallerLanguage.
 * Generated by PHPUnit on 2012-02-29 at 17:41:33.
 */
class JInstallerLanguageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JInstallerLanguage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JInstallerLanguage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JInstallerLanguage::install
     * @todo Implement testInstall().
     */
    public function testInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLanguage::update
     * @todo Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLanguage::uninstall
     * @todo Implement testUninstall().
     */
    public function testUninstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLanguage::discover
     * @todo Implement testDiscover().
     */
    public function testDiscover() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLanguage::discover_install
     * @todo Implement testDiscover_install().
     */
    public function testDiscover_install() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLanguage::refreshManifestCache
     * @todo Implement testRefreshManifestCache().
     */
    public function testRefreshManifestCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
