<?php

require_once JPATH_PLATFORM.'/joomla/installer/adapters/library.php';

/**
 * Test class for JInstallerLibrary.
 * Generated by PHPUnit on 2012-02-29 at 17:41:34.
 */
class JInstallerLibraryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JInstallerLibrary
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JInstallerLibrary;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JInstallerLibrary::loadLanguage
     * @todo Implement testLoadLanguage().
     */
    public function testLoadLanguage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLibrary::install
     * @todo Implement testInstall().
     */
    public function testInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLibrary::update
     * @todo Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLibrary::uninstall
     * @todo Implement testUninstall().
     */
    public function testUninstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLibrary::discover
     * @todo Implement testDiscover().
     */
    public function testDiscover() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLibrary::discover_install
     * @todo Implement testDiscover_install().
     */
    public function testDiscover_install() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerLibrary::refreshManifestCache
     * @todo Implement testRefreshManifestCache().
     */
    public function testRefreshManifestCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
