<?php

require_once JPATH_PLATFORM.'/joomla/installer/adapters/component.php';

/**
 * Test class for JInstallerComponent.
 * Generated by PHPUnit on 2012-02-29 at 17:41:34.
 */
class JInstallerComponentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JInstallerComponent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JInstallerComponent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JInstallerComponent::loadLanguage
     * @todo Implement testLoadLanguage().
     */
    public function testLoadLanguage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerComponent::install
     * @todo Implement testInstall().
     */
    public function testInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerComponent::update
     * @todo Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerComponent::uninstall
     * @todo Implement testUninstall().
     */
    public function testUninstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerComponent::discover
     * @todo Implement testDiscover().
     */
    public function testDiscover() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerComponent::discover_install
     * @todo Implement testDiscover_install().
     */
    public function testDiscover_install() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerComponent::refreshManifestCache
     * @todo Implement testRefreshManifestCache().
     */
    public function testRefreshManifestCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
