<?php

require_once JPATH_PLATFORM.'/joomla/database/driver/mysql.php';

/**
 * Test class for JDatabaseDriverMysql.
 * Generated by PHPUnit on 2012-02-29 at 17:41:44.
 */
class JDatabaseDriverMysqlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDatabaseDriverMysql
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JDatabaseDriverMysql;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JDatabaseDriverMysql::connect
     * @todo Implement testConnect().
     */
    public function testConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::escape
     * @todo Implement testEscape().
     */
    public function testEscape() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::isSupported
     * @todo Implement testIsSupported().
     */
    public function testIsSupported() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::connected
     * @todo Implement testConnected().
     */
    public function testConnected() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::dropTable
     * @todo Implement testDropTable().
     */
    public function testDropTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::getAffectedRows
     * @todo Implement testGetAffectedRows().
     */
    public function testGetAffectedRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::getCollation
     * @todo Implement testGetCollation().
     */
    public function testGetCollation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::getNumRows
     * @todo Implement testGetNumRows().
     */
    public function testGetNumRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::getTableCreate
     * @todo Implement testGetTableCreate().
     */
    public function testGetTableCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::getTableColumns
     * @todo Implement testGetTableColumns().
     */
    public function testGetTableColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::getTableKeys
     * @todo Implement testGetTableKeys().
     */
    public function testGetTableKeys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::getTableList
     * @todo Implement testGetTableList().
     */
    public function testGetTableList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::getVersion
     * @todo Implement testGetVersion().
     */
    public function testGetVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::insertid
     * @todo Implement testInsertid().
     */
    public function testInsertid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::lockTable
     * @todo Implement testLockTable().
     */
    public function testLockTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::execute
     * @todo Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::renameTable
     * @todo Implement testRenameTable().
     */
    public function testRenameTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::select
     * @todo Implement testSelect().
     */
    public function testSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::setUTF
     * @todo Implement testSetUTF().
     */
    public function testSetUTF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::transactionCommit
     * @todo Implement testTransactionCommit().
     */
    public function testTransactionCommit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::transactionRollback
     * @todo Implement testTransactionRollback().
     */
    public function testTransactionRollback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::transactionStart
     * @todo Implement testTransactionStart().
     */
    public function testTransactionStart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysql::unlockTables
     * @todo Implement testUnlockTables().
     */
    public function testUnlockTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
