<?php

require_once JPATH_PLATFORM.'/joomla/database/driver/oracle.php';

/**
 * Test class for JDatabaseDriverOracle.
 * Generated by PHPUnit on 2012-02-29 at 17:41:44.
 */
class JDatabaseDriverOracleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDatabaseDriverOracle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JDatabaseDriverOracle;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JDatabaseDriverOracle::connect
     * @todo Implement testConnect().
     */
    public function testConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::dropTable
     * @todo Implement testDropTable().
     */
    public function testDropTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::getCollation
     * @todo Implement testGetCollation().
     */
    public function testGetCollation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::getDateFormat
     * @todo Implement testGetDateFormat().
     */
    public function testGetDateFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::getTableCreate
     * @todo Implement testGetTableCreate().
     */
    public function testGetTableCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::getTableColumns
     * @todo Implement testGetTableColumns().
     */
    public function testGetTableColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::getTableKeys
     * @todo Implement testGetTableKeys().
     */
    public function testGetTableKeys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::getTableList
     * @todo Implement testGetTableList().
     */
    public function testGetTableList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::getVersion
     * @todo Implement testGetVersion().
     */
    public function testGetVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::select
     * @todo Implement testSelect().
     */
    public function testSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::setDateFormat
     * @todo Implement testSetDateFormat().
     */
    public function testSetDateFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::setUTF
     * @todo Implement testSetUTF().
     */
    public function testSetUTF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::lockTable
     * @todo Implement testLockTable().
     */
    public function testLockTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::renameTable
     * @todo Implement testRenameTable().
     */
    public function testRenameTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::unlockTables
     * @todo Implement testUnlockTables().
     */
    public function testUnlockTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverOracle::isSupported
     * @todo Implement testIsSupported().
     */
    public function testIsSupported() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
