<?php

require_once JPATH_PLATFORM.'/joomla/database/driver/mysqli.php';

/**
 * Test class for JDatabaseDriverMysqli.
 * Generated by PHPUnit on 2012-02-29 at 17:41:44.
 */
class JDatabaseDriverMysqliTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDatabaseDriverMysqli
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JDatabaseDriverMysqli;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JDatabaseDriverMysqli::connect
     * @todo Implement testConnect().
     */
    public function testConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::escape
     * @todo Implement testEscape().
     */
    public function testEscape() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::isSupported
     * @todo Implement testIsSupported().
     */
    public function testIsSupported() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::connected
     * @todo Implement testConnected().
     */
    public function testConnected() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::getAffectedRows
     * @todo Implement testGetAffectedRows().
     */
    public function testGetAffectedRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::getNumRows
     * @todo Implement testGetNumRows().
     */
    public function testGetNumRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::getVersion
     * @todo Implement testGetVersion().
     */
    public function testGetVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::insertid
     * @todo Implement testInsertid().
     */
    public function testInsertid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::execute
     * @todo Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::select
     * @todo Implement testSelect().
     */
    public function testSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverMysqli::setUTF
     * @todo Implement testSetUTF().
     */
    public function testSetUTF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
