<?php

require_once JPATH_PLATFORM.'/joomla/database/driver/sqlite.php';

/**
 * Test class for JDatabaseDriverSqlite.
 * Generated by PHPUnit on 2012-02-29 at 17:41:43.
 */
class JDatabaseDriverSqliteTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDatabaseDriverSqlite
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JDatabaseDriverSqlite;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JDatabaseDriverSqlite::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::dropTable
     * @todo Implement testDropTable().
     */
    public function testDropTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::getCollation
     * @todo Implement testGetCollation().
     */
    public function testGetCollation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::getTableCreate
     * @todo Implement testGetTableCreate().
     */
    public function testGetTableCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::getTableColumns
     * @todo Implement testGetTableColumns().
     */
    public function testGetTableColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::getTableKeys
     * @todo Implement testGetTableKeys().
     */
    public function testGetTableKeys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::getTableList
     * @todo Implement testGetTableList().
     */
    public function testGetTableList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::getVersion
     * @todo Implement testGetVersion().
     */
    public function testGetVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::select
     * @todo Implement testSelect().
     */
    public function testSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::setUTF
     * @todo Implement testSetUTF().
     */
    public function testSetUTF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::lockTable
     * @todo Implement testLockTable().
     */
    public function testLockTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::renameTable
     * @todo Implement testRenameTable().
     */
    public function testRenameTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::unlockTables
     * @todo Implement testUnlockTables().
     */
    public function testUnlockTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriverSqlite::isSupported
     * @todo Implement testIsSupported().
     */
    public function testIsSupported() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
