<?php

require_once JPATH_PLATFORM.'/joomla/crypt/cipher/mcrypt.php';

/**
 * Test class for JCryptCipherMcrypt.
 * Generated by PHPUnit on 2012-02-29 at 17:41:23.
 */
class JCryptCipherMcryptTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JCryptCipherMcrypt
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JCryptCipherMcrypt;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JCryptCipherMcrypt::decrypt
     * @todo Implement testDecrypt().
     */
    public function testDecrypt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCryptCipherMcrypt::encrypt
     * @todo Implement testEncrypt().
     */
    public function testEncrypt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCryptCipherMcrypt::generateKey
     * @todo Implement testGenerateKey().
     */
    public function testGenerateKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCryptCipherMcrypt::pbkdf2
     * @todo Implement testPbkdf2().
     */
    public function testPbkdf2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
