<?php
/**
 * @package     Joomla.UnitTest
 *
 * @copyright   Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

include_once JPATH_PLATFORM . '/joomla/database/database/sqlazurequery.php';

/**
 * Test class for JDatabaseQuerySQLAzure.
 * Generated by PHPUnit on 2011-10-26 at 19:37:39.
 */
class JDatabaseQuerySQLAzureTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDatabaseQuerySQLAzure
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JDatabaseQuerySQLAzure;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

	/**
	 * @todo Decide how to Implement.
	 */
	public function testDummy()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}

?>
