<?php

require_once JPATH_PLATFORM.'/joomla/html/html/contentlanguage.php';

/**
 * Test class for JHtmlContentLanguage.
 * Generated by PHPUnit on 2012-02-29 at 17:41:30.
 */
class JHtmlContentLanguageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JHtmlContentLanguage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JHtmlContentLanguage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JHtmlContentLanguage::existing
     * @todo Implement testExisting().
     */
    public function testExisting() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
