<?php

require_once JPATH_PLATFORM.'/joomla/html/html/tabs.php';

/**
 * Test class for JHtmlTabs.
 * Generated by PHPUnit on 2012-02-29 at 17:41:27.
 */
class JHtmlTabsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JHtmlTabs
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JHtmlTabs;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JHtmlTabs::start
     * @todo Implement testStart().
     */
    public function testStart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JHtmlTabs::end
     * @todo Implement testEnd().
     */
    public function testEnd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JHtmlTabs::panel
     * @todo Implement testPanel().
     */
    public function testPanel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
