<?php
/**
 * @package     Joomla.UnitTest
 * @subpackage  HTML
 *
 * @copyright   Copyright (C) 2005 - 2012 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

require_once JPATH_PLATFORM . '/cms//toolbar/button.php';

require_once dirname(__FILE__).'/JButtonMock.php';

/**
 * Test class for JButton.
 * Generated by PHPUnit on 2009-10-27 at 16:59:36.
 */
class JToolbarButtonTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var JButton
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new JButtonMock;
	}

	/**
	 * Test JButton::__construct().
	 */
	public function test__construct()
	{
		$object = new JButtonMock('test');
		
		$this->assertThat(
			$object->_parent,
			$this->equalTo('test')
		);
	}

	/**
	 * Test JButton::getName().
	 */
	public function testGetName()
	{
		$this->assertThat(
			$this->object->getName(),
			$this->equalTo('Mock')
		);
	}

	/**
	 * Test JButton::render().
	 */
	public function testRender()
	{
		$array = array();
		$this->assertThat(
			$this->object->render($array),
			$this->equalTo("<li class=\"button\" id=\"mock-id\">\nmock-button</li>\n")
		);
	}

	/**
	 * Test JButton::fetchIconClass().
	 */
	public function testFetchIconClass()
	{
		$this->assertThat(
			$this->object->fetchIconClass('mock'),
			$this->equalTo('icon-32-mock')
		);
	}

	/**
	 * Test JButton::fetchId().
	 */
	public function testFetchId()
	{
		$this->assertThat(
			$this->object->fetchId(),
			$this->equalTo('mock-id')
		);
	}
}
