<?php

require_once JPATH_PLATFORM.'/joomla/cache/storage/memcached.php';

/**
 * Test class for JCacheStorageMemcached.
 * Generated by PHPUnit on 2012-02-29 at 17:41:24.
 */
class JCacheStorageMemcachedTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JCacheStorageMemcached
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JCacheStorageMemcached;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JCacheStorageMemcached::get
     * @todo Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCacheStorageMemcached::getAll
     * @todo Implement testGetAll().
     */
    public function testGetAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCacheStorageMemcached::store
     * @todo Implement testStore().
     */
    public function testStore() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCacheStorageMemcached::remove
     * @todo Implement testRemove().
     */
    public function testRemove() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCacheStorageMemcached::clean
     * @todo Implement testClean().
     */
    public function testClean() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCacheStorageMemcached::isSupported
     * @todo Implement testIsSupported().
     */
    public function testIsSupported() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCacheStorageMemcached::lock
     * @todo Implement testLock().
     */
    public function testLock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCacheStorageMemcached::unlock
     * @todo Implement testUnlock().
     */
    public function testUnlock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
