<?php
/**
 * @package     Joomla.UnitTest
 *
 * @copyright   Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

include_once JPATH_PLATFORM . '/libraries/joomla/form/fields/groupedlist.php';

/**
 * Test class for JFormFieldGroupedList.
 * Generated by PHPUnit on 2011-10-26 at 19:35:40.
 */
class JFormFieldGroupedListTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JFormFieldGroupedList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JFormFieldGroupedList;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
