<?php

require_once JPATH_PLATFORM.'/joomla/installer/installer.php';

/**
 * Test class for JInstaller.
 * Generated by PHPUnit on 2012-02-29 at 17:40:48.
 */
class JInstallerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JInstaller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JInstaller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JInstaller::getInstance
     * @todo Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::isOverwrite
     * @todo Implement testIsOverwrite().
     */
    public function testIsOverwrite() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::setOverwrite
     * @todo Implement testSetOverwrite().
     */
    public function testSetOverwrite() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::getRedirectURL
     * @todo Implement testGetRedirectURL().
     */
    public function testGetRedirectURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::setRedirectURL
     * @todo Implement testSetRedirectURL().
     */
    public function testSetRedirectURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::isUpgrade
     * @todo Implement testIsUpgrade().
     */
    public function testIsUpgrade() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::setUpgrade
     * @todo Implement testSetUpgrade().
     */
    public function testSetUpgrade() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::getManifest
     * @todo Implement testGetManifest().
     */
    public function testGetManifest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::getPath
     * @todo Implement testGetPath().
     */
    public function testGetPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::setPath
     * @todo Implement testSetPath().
     */
    public function testSetPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::pushStep
     * @todo Implement testPushStep().
     */
    public function testPushStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::abort
     * @todo Implement testAbort().
     */
    public function testAbort() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::install
     * @todo Implement testInstall().
     */
    public function testInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::discover_install
     * @todo Implement testDiscover_install().
     */
    public function testDiscover_install() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::discover
     * @todo Implement testDiscover().
     */
    public function testDiscover() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::update
     * @todo Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::uninstall
     * @todo Implement testUninstall().
     */
    public function testUninstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::refreshManifestCache
     * @todo Implement testRefreshManifestCache().
     */
    public function testRefreshManifestCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::setupInstall
     * @todo Implement testSetupInstall().
     */
    public function testSetupInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::parseQueries
     * @todo Implement testParseQueries().
     */
    public function testParseQueries() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::parseSQLFiles
     * @todo Implement testParseSQLFiles().
     */
    public function testParseSQLFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::setSchemaVersion
     * @todo Implement testSetSchemaVersion().
     */
    public function testSetSchemaVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::parseSchemaUpdates
     * @todo Implement testParseSchemaUpdates().
     */
    public function testParseSchemaUpdates() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::parseFiles
     * @todo Implement testParseFiles().
     */
    public function testParseFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::parseLanguages
     * @todo Implement testParseLanguages().
     */
    public function testParseLanguages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::parseMedia
     * @todo Implement testParseMedia().
     */
    public function testParseMedia() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::getParams
     * @todo Implement testGetParams().
     */
    public function testGetParams() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::copyFiles
     * @todo Implement testCopyFiles().
     */
    public function testCopyFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::removeFiles
     * @todo Implement testRemoveFiles().
     */
    public function testRemoveFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::copyManifest
     * @todo Implement testCopyManifest().
     */
    public function testCopyManifest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::findManifest
     * @todo Implement testFindManifest().
     */
    public function testFindManifest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::isManifest
     * @todo Implement testIsManifest().
     */
    public function testIsManifest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::generateManifestCache
     * @todo Implement testGenerateManifestCache().
     */
    public function testGenerateManifestCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::cleanDiscoveredExtension
     * @todo Implement testCleanDiscoveredExtension().
     */
    public function testCleanDiscoveredExtension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::findDeletedFiles
     * @todo Implement testFindDeletedFiles().
     */
    public function testFindDeletedFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::loadMD5Sum
     * @todo Implement testLoadMD5Sum().
     */
    public function testLoadMD5Sum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstaller::parseXMLInstallFile
     * @todo Implement testParseXMLInstallFile().
     */
    public function testParseXMLInstallFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
