<?php

require_once JPATH_PLATFORM.'/joomla/installer/helper.php';

/**
 * Test class for JInstallerHelper.
 * Generated by PHPUnit on 2012-02-29 at 17:40:49.
 */
class JInstallerHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JInstallerHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JInstallerHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JInstallerHelper::downloadPackage
     * @todo Implement testDownloadPackage().
     */
    public function testDownloadPackage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerHelper::unpack
     * @todo Implement testUnpack().
     */
    public function testUnpack() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerHelper::detectType
     * @todo Implement testDetectType().
     */
    public function testDetectType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerHelper::getFilenameFromURL
     * @todo Implement testGetFilenameFromURL().
     */
    public function testGetFilenameFromURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerHelper::cleanupInstall
     * @todo Implement testCleanupInstall().
     */
    public function testCleanupInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JInstallerHelper::splitSql
     * @todo Implement testSplitSql().
     */
    public function testSplitSql() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
