<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/installer/packagemanifest.php';

/**
 * Test class for JPackageManifest.
 * Generated by PHPUnit on 2012-02-29 at 17:40:48.
 */
class JPackageManifestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JPackageManifest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JPackageManifest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JPackageManifest::loadManifestFromXML
     * @todo Implement testLoadManifestFromXML().
     */
    public function testLoadManifestFromXML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
