<?php

require_once JPATH_PLATFORM.'/joomla/document/image/image.php';

/**
 * Test class for JDocumentImage.
 * Generated by PHPUnit on 2012-02-29 at 17:41:36.
 */
class JDocumentImageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDocumentImage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JDocumentImage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JDocumentImage::render
     * @todo Implement testRender().
     */
    public function testRender() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
