<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-12 at 18:56:08.
 */
class JMediawikiLinksTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var JMediawikiLinks
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new JMediawikiLinks;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers JMediawikiLinks::getLinks
     * @todo   Implement testGetLinks().
     */
    public function testGetLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiLinks::getLinksUsed
     * @todo   Implement testGetLinksUsed().
     */
    public function testGetLinksUsed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiLinks::getIWLinks
     * @todo   Implement testGetIWLinks().
     */
    public function testGetIWLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiLinks::getLangLinks
     * @todo   Implement testGetLangLinks().
     */
    public function testGetLangLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiLinks::getExtLinks
     * @todo   Implement testGetExtLinks().
     */
    public function testGetExtLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiLinks::enumerateLinks
     * @todo   Implement testEnumerateLinks().
     */
    public function testEnumerateLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
