<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-12 at 18:56:49.
 */
class JMediawikiPagesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var JMediawikiPages
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new JMediawikiPages;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers JMediawikiPages::editPage
     * @todo   Implement testEditPage().
     */
    public function testEditPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::deletePageByName
     * @todo   Implement testDeletePageByName().
     */
    public function testDeletePageByName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::deletePageByID
     * @todo   Implement testDeletePageByID().
     */
    public function testDeletePageByID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::undeletePage
     * @todo   Implement testUndeletePage().
     */
    public function testUndeletePage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::movePageByName
     * @todo   Implement testMovePageByName().
     */
    public function testMovePageByName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::movePageByID
     * @todo   Implement testMovePageByID().
     */
    public function testMovePageByID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::rollback
     * @todo   Implement testRollback().
     */
    public function testRollback()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::changeProtection
     * @todo   Implement testChangeProtection().
     */
    public function testChangeProtection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getPageInfo
     * @todo   Implement testGetPageInfo().
     */
    public function testGetPageInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getPageProperties
     * @todo   Implement testGetPageProperties().
     */
    public function testGetPageProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getRevisions
     * @todo   Implement testGetRevisions().
     */
    public function testGetRevisions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getDeletedRevisions
     * @todo   Implement testGetDeletedRevisions().
     */
    public function testGetDeletedRevisions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getPageTemplates
     * @todo   Implement testGetPageTemplates().
     */
    public function testGetPageTemplates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getBackLinks
     * @todo   Implement testGetBackLinks().
     */
    public function testGetBackLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getIWBackLinks
     * @todo   Implement testGetIWBackLinks().
     */
    public function testGetIWBackLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getLangBackLinks
     * @todo   Implement testGetLangBackLinks().
     */
    public function testGetLangBackLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getCategoryPagesByname
     * @todo   Implement testGetCategoryPagesByname().
     */
    public function testGetCategoryPagesByname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getCategoryPagesByID
     * @todo   Implement testGetCategoryPagesByID().
     */
    public function testGetCategoryPagesByID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getImageUsage
     * @todo   Implement testGetImageUsage().
     */
    public function testGetImageUsage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiPages::getToken
     * @todo   Implement testGetToken().
     */
    public function testGetToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
