<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-12 at 18:57:10.
 */
class JMediawikiSitesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var JMediawikiSites
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new JMediawikiSites;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers JMediawikiSites::getSiteInfo
     * @todo   Implement testGetSiteInfo().
     */
    public function testGetSiteInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiSites::getEvents
     * @todo   Implement testGetEvents().
     */
    public function testGetEvents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiSites::getRecentChanges
     * @todo   Implement testGetRecentChanges().
     */
    public function testGetRecentChanges()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiSites::getProtectedTitles
     * @todo   Implement testGetProtectedTitles().
     */
    public function testGetProtectedTitles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
