<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-12 at 18:55:19.
 */
class JMediawikiCategoriesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var JMediawikiCategories
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new JMediawikiCategories;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers JMediawikiCategories::getCategories
     * @todo   Implement testGetCategories().
     */
    public function testGetCategories()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiCategories::getCategoriesUsed
     * @todo   Implement testGetCategoriesUsed().
     */
    public function testGetCategoriesUsed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiCategories::getCategoriesInfo
     * @todo   Implement testGetCategoriesInfo().
     */
    public function testGetCategoriesInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiCategories::enumerateCategories
     * @todo   Implement testEnumerateCategories().
     */
    public function testEnumerateCategories()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiCategories::getChangeTags
     * @todo   Implement testGetChangeTags().
     */
    public function testGetChangeTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
