<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-12 at 18:57:18.
 */
class JMediawikiUsersTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var JMediawikiUsers
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new JMediawikiUsers;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers JMediawikiUsers::login
     * @todo   Implement testLogin().
     */
    public function testLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiUsers::logout
     * @todo   Implement testLogout().
     */
    public function testLogout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiUsers::getUserInfo
     * @todo   Implement testGetUserInfo().
     */
    public function testGetUserInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiUsers::getCurrentUserInfo
     * @todo   Implement testGetCurrentUserInfo().
     */
    public function testGetCurrentUserInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiUsers::getUserContribs
     * @todo   Implement testGetUserContribs().
     */
    public function testGetUserContribs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiUsers::blockUser
     * @todo   Implement testBlockUser().
     */
    public function testBlockUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiUsers::unBlockUserByName
     * @todo   Implement testUnBlockUserByName().
     */
    public function testUnBlockUserByName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiUsers::unBlockUserByID
     * @todo   Implement testUnBlockUserByID().
     */
    public function testUnBlockUserByID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiUsers::assignGroup
     * @todo   Implement testAssignGroup().
     */
    public function testAssignGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiUsers::emailUser
     * @todo   Implement testEmailUser().
     */
    public function testEmailUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiUsers::getToken
     * @todo   Implement testGetToken().
     */
    public function testGetToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
