<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-12 at 18:55:58.
 */
class JMediawikiImagesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var JMediawikiImages
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new JMediawikiImages;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers JMediawikiImages::getImages
     * @todo   Implement testGetImages().
     */
    public function testGetImages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiImages::getImagesUsed
     * @todo   Implement testGetImagesUsed().
     */
    public function testGetImagesUsed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiImages::getImageInfo
     * @todo   Implement testGetImageInfo().
     */
    public function testGetImageInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JMediawikiImages::enumerateImages
     * @todo   Implement testEnumerateImages().
     */
    public function testEnumerateImages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
