<?php

require_once JPATH_PLATFORM.'/joomla/application/base.php';

/**
 * Test class for JApplicationBase.
 * Generated by PHPUnit on 2012-02-29 at 17:40:35.
 */
class JApplicationBaseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JApplicationBase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JApplicationBase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JApplicationBase::close
     * @todo Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JApplicationBase::registerEvent
     * @todo Implement testRegisterEvent().
     */
    public function testRegisterEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JApplicationBase::triggerEvent
     * @todo Implement testTriggerEvent().
     */
    public function testTriggerEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
