<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/application/route.php';

/**
 * Test class for JRoute.
 * Generated by PHPUnit on 2012-02-29 at 17:40:34.
 */
class JRouteTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JRoute
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JRoute;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JRoute::_
     * @todo Implement test_().
     */
    public function test_() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
