<?php

require_once JPATH_PLATFORM.'/joomla/http/factory.php';

/**
 * Test class for JHttpFactory.
 * Generated by PHPUnit on 2012-02-29 at 17:40:38.
 */
class JHttpFactoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JHttpFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JHttpFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JHttpFactory::getHttp
     * @todo Implement testGetHttp().
     */
    public function testGetHttp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JHttpFactory::getAvailableDriver
     * @todo Implement testGetAvailableDriver().
     */
    public function testGetAvailableDriver() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JHttpFactory::getHttpTransports
     * @todo Implement testGetHttpTransports().
     */
    public function testGetHttpTransports() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
