<?php

require_once JPATH_PLATFORM.'/joomla/image/filters/negate.php';

/**
 * Test class for JImageFilterNegate.
 * Generated by PHPUnit on 2012-02-29 at 17:41:50.
 */
class JImageFilterNegateTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JImageFilterNegate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JImageFilterNegate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JImageFilterNegate::execute
     * @todo Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
