<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/language/transliterate.php';

/**
 * Test class for JLanguageTransliterate.
 * Generated by PHPUnit on 2012-02-29 at 17:40:44.
 */
class JLanguageTransliterateTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JLanguageTransliterate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JLanguageTransliterate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JLanguageTransliterate::utf8_latin_to_ascii
     * @todo Implement testUtf8_latin_to_ascii().
     */
    public function testUtf8_latin_to_ascii() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
