<?php
/**
 * @package     Joomla.UnitTest
 *
 * @copyright   Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

include_once JPATH_PLATFORM . '/joomla/language/latin_transliterate.php';

/**
 * Test class for JLanguageTransliterate.
 * Generated by PHPUnit on 2011-10-26 at 19:34:06.
 */
class JLanguageTransliterateTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JLanguageTransliterate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JLanguageTransliterate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testUtf8_latin_to_ascii().
     */
    public function testUtf8_latin_to_ascii() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
