<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/language/text.php';

/**
 * Test class for JText.
 * Generated by PHPUnit on 2012-02-29 at 17:40:44.
 */
class JTextTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JText
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JText;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JText::_
     * @todo Implement test_().
     */
    public function test_() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JText::alt
     * @todo Implement testAlt().
     */
    public function testAlt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JText::plural
     * @todo Implement testPlural().
     */
    public function testPlural() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JText::sprintf
     * @todo Implement testSprintf().
     */
    public function testSprintf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JText::printf
     * @todo Implement testPrintf().
     */
    public function testPrintf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JText::script
     * @todo Implement testScript().
     */
    public function testScript() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
