<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/form/helper.php';

/**
 * Test class for JFormHelper.
 * Generated by PHPUnit on 2012-02-29 at 17:40:37.
 */
class JFormHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JFormHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JFormHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JFormHelper::loadFieldType
     * @todo Implement testLoadFieldType().
     */
    public function testLoadFieldType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JFormHelper::loadRuleType
     * @todo Implement testLoadRuleType().
     */
    public function testLoadRuleType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JFormHelper::loadFieldClass
     * @todo Implement testLoadFieldClass().
     */
    public function testLoadFieldClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JFormHelper::loadRuleClass
     * @todo Implement testLoadRuleClass().
     */
    public function testLoadRuleClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JFormHelper::addFieldPath
     * @todo Implement testAddFieldPath().
     */
    public function testAddFieldPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JFormHelper::addFormPath
     * @todo Implement testAddFormPath().
     */
    public function testAddFormPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JFormHelper::addRulePath
     * @todo Implement testAddRulePath().
     */
    public function testAddRulePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
