<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/database/factory.php';

/**
 * Test class for JDatabaseFactory.
 * Generated by PHPUnit on 2012-02-29 at 17:40:52.
 */
class JDatabaseFactoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDatabaseFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JDatabaseFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JDatabaseFactory::getDriver
     * @todo Implement testGetDriver().
     */
    public function testGetDriver() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseFactory::getExporter
     * @todo Implement testGetExporter().
     */
    public function testGetExporter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseFactory::getImporter
     * @todo Implement testGetImporter().
     */
    public function testGetImporter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseFactory::getInstance
     * @todo Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseFactory::getQuery
     * @todo Implement testGetQuery().
     */
    public function testGetQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseFactory::getTable
     * @todo Implement testGetTable().
     */
    public function testGetTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseFactory::setInstance
     * @todo Implement testSetInstance().
     */
    public function testSetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
