<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/database/driver.php';

/**
 * Test class for JDatabaseDriver.
 * Generated by PHPUnit on 2012-02-29 at 17:40:52.
 */
class JDatabaseDriverTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDatabaseDriver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JDatabaseDriver;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JDatabaseDriver::getConnectors
     * @todo Implement testGetConnectors().
     */
    public function testGetConnectors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getInstance
     * @todo Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::splitSql
     * @todo Implement testSplitSql().
     */
    public function testSplitSql() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::__call
     * @todo Implement test__call().
     */
    public function test__call() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getConnection
     * @todo Implement testGetConnection().
     */
    public function testGetConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getCount
     * @todo Implement testGetCount().
     */
    public function testGetCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getDateFormat
     * @todo Implement testGetDateFormat().
     */
    public function testGetDateFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getLog
     * @todo Implement testGetLog().
     */
    public function testGetLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getMinimum
     * @todo Implement testGetMinimum().
     */
    public function testGetMinimum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getNullDate
     * @todo Implement testGetNullDate().
     */
    public function testGetNullDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getPrefix
     * @todo Implement testGetPrefix().
     */
    public function testGetPrefix() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getExporter
     * @todo Implement testGetExporter().
     */
    public function testGetExporter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getImporter
     * @todo Implement testGetImporter().
     */
    public function testGetImporter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getQuery
     * @todo Implement testGetQuery().
     */
    public function testGetQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::getUTFSupport
     * @todo Implement testGetUTFSupport().
     */
    public function testGetUTFSupport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::hasUTFSupport
     * @todo Implement testHasUTFSupport().
     */
    public function testHasUTFSupport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::insertObject
     * @todo Implement testInsertObject().
     */
    public function testInsertObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::isMinimumVersion
     * @todo Implement testIsMinimumVersion().
     */
    public function testIsMinimumVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::loadAssoc
     * @todo Implement testLoadAssoc().
     */
    public function testLoadAssoc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::loadAssocList
     * @todo Implement testLoadAssocList().
     */
    public function testLoadAssocList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::loadColumn
     * @todo Implement testLoadColumn().
     */
    public function testLoadColumn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::loadNextObject
     * @todo Implement testLoadNextObject().
     */
    public function testLoadNextObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::loadNextRow
     * @todo Implement testLoadNextRow().
     */
    public function testLoadNextRow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::loadObject
     * @todo Implement testLoadObject().
     */
    public function testLoadObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::loadObjectList
     * @todo Implement testLoadObjectList().
     */
    public function testLoadObjectList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::loadResult
     * @todo Implement testLoadResult().
     */
    public function testLoadResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::loadRow
     * @todo Implement testLoadRow().
     */
    public function testLoadRow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::loadRowList
     * @todo Implement testLoadRowList().
     */
    public function testLoadRowList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::quote
     * @todo Implement testQuote().
     */
    public function testQuote() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::quoteName
     * @todo Implement testQuoteName().
     */
    public function testQuoteName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::replacePrefix
     * @todo Implement testReplacePrefix().
     */
    public function testReplacePrefix() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::setDebug
     * @todo Implement testSetDebug().
     */
    public function testSetDebug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::setQuery
     * @todo Implement testSetQuery().
     */
    public function testSetQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::truncateTable
     * @todo Implement testTruncateTable().
     */
    public function testTruncateTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseDriver::updateObject
     * @todo Implement testUpdateObject().
     */
    public function testUpdateObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
