<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/updater/update.php';

/**
 * Test class for JUpdate.
 * Generated by PHPUnit on 2012-02-29 at 17:40:30.
 */
class JUpdateTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JUpdate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JUpdate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JUpdate::_startElement
     * @todo Implement test_startElement().
     */
    public function test_startElement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUpdate::_endElement
     * @todo Implement test_endElement().
     */
    public function test_endElement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUpdate::_characterData
     * @todo Implement test_characterData().
     */
    public function test_characterData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUpdate::loadFromXML
     * @todo Implement testLoadFromXML().
     */
    public function testLoadFromXML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
