<?php
/**
 * @package     Joomla.UnitTest
 * @subpackage  Base
 *
 * @copyright   Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

require_once JPATH_PLATFORM.'/joomla/base/observable.php';

/**
 * Test class for JObservable.
 * Generated by PHPUnit on 2009-10-08 at 11:45:30.
 */
class JObservableTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var	JObservable
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new JObservable;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * Uses an extended version of JObservable to test the state getter.
	 */
	public function testGetState() {
		require_once JPATH_TESTS.'/objects/JObservableTester.php';
		$tester = new JObservableTester;
		$this->assertEquals(
			$tester->setState( 12 ),
			$tester->getState(),
			"Should get back what I set"
		);
	}

	/**
	 * @todo Implement testNotify().
	 */
	public function testNotify() {
		require_once JPATH_PLATFORM.'/joomla/plugin/plugin.php';
		$tester = $this->getMock('JObserver', array('update'), array(&$this->object));
		$tester->expects($this->once())->method('update');
		$this->object->notify();
	}

	/**
	 * 
	 */
	public function testAttachAndDetach() {
		require_once JPATH_PLATFORM.'/joomla/plugin/plugin.php';
		$tester = $this->getMock('JObserver', array('update'), array(),'',false);
		$this->object->attach($tester);
		$this->assertAttributeEquals(
			array($tester),
			'_observers',
			$this->object
		);
		$this->object->detach($tester);
		$this->assertAttributeEquals(
			array(),
			'_observers',
			$this->object
		);
	}

}

