<?php

require_once JPATH_PLATFORM.'/joomla/form/rules/url.php';

/**
 * Test class for JFormRuleUrl.
 * Generated by PHPUnit on 2012-02-29 at 17:41:09.
 */
class JFormRuleUrlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JFormRuleUrl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JFormRuleUrl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JFormRuleUrl::test
     * @todo Implement testTest().
     */
    public function testTest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
