<?php
/**
 * @package     Joomla.UnitTest
 *
 * @copyright   Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

include_once JPATH_PLATFORM . '/joomla/input/files.php';

/**
 * Test class for JInputFiles.
 * Generated by PHPUnit on 2011-10-26 at 19:37:42.
 */
class JInputFilesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var JInputFiles
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
	{
        $this->object = new JInputFiles;
    }

	/**
	 * Test the JInputFiles::get method.
	 *
	 * @since   12.2
	 *
	 * @return  void
	 */
    public function testGet()
	{
		$value = array(
			'name' => 'foo',
			'type' => 'foo',
			'tmp_name' => 'foo',
			'error' => 'foo',
			'size' => 'foo'
		);

		$_FILES['test'] = $value;

		$this->assertEquals($this->object->get('test'), $value);
    }

    /**
     * Test the JInputFiles::set method.
	 *
	 * @since   12.2
	 *
	 * @return  void
     */
    public function testSet()
	{
		// Test with a correct value.
		$value = array(
			'name' => 'foo',
			'type' => 'foo',
			'tmp_name' => 'foo',
			'error' => 'foo',
			'size' => 'foo'
		);

		$this->object->set('test', $value);
		$this->assertEquals($this->object->get('test'), $value);

		// Test with more keys than needed.
		$value = array(
			'name' => 'foo',
			'type' => 'foo',
			'tmp_name' => 'foo',
			'error' => 'foo',
			'size' => 'foo',
			'foo' => 'foo'
		);

		$this->object->set('test', $value);
		$file = $this->object->get('test');

		$this->assertEquals($file['name'], 'foo');
		$this->assertEquals($file['type'], 'foo');
		$this->assertEquals($file['tmp_name'], 'foo');
		$this->assertEquals($file['error'], 'foo');
		$this->assertEquals($file['size'], 'foo');

		// Assert the useless value has been ignored.
		$this->assertFalse(isset($file['foo']));
	}

	/**
	 * Test the JInputFiles::set method exception, when value has less keys than needed.
	 *
	 * @since   12.2
	 *
	 * @expectedException  InvalidArgumentException
	 * @return  void
	 */
	public function testSetExceptionValueLess()
	{
		$value = array(
			'name' => 'foo',
			'type' => 'foo',
			'tmp_name' => 'foo',
			'error' => 'foo',
		);

		$this->object->set('test', $value);
	}

	/**
	 * Test the JInputFiles::set method exception, when value is not an array.
	 *
	 * @since   12.2
	 *
	 * @expectedException  InvalidArgumentException
	 * @return  void
	 */
	public function testSetExceptionValueNotArray()
	{
		$this->object->set('foo', 'bar');
	}
}
