<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/crypt/key.php';

/**
 * Test class for JCryptKey.
 * Generated by PHPUnit on 2012-02-29 at 17:40:46.
 */
class JCryptKeyTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JCryptKey
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JCryptKey;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JCryptKey::__get
     * @todo Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
