<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/crypt/crypt.php';

/**
 * Test class for JCrypt.
 * Generated by PHPUnit on 2012-02-29 at 17:40:45.
 */
class JCryptTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JCrypt
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JCrypt;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JCrypt::decrypt
     * @todo Implement testDecrypt().
     */
    public function testDecrypt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCrypt::encrypt
     * @todo Implement testEncrypt().
     */
    public function testEncrypt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCrypt::generateKey
     * @todo Implement testGenerateKey().
     */
    public function testGenerateKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JCrypt::setKey
     * @todo Implement testSetKey().
     */
    public function testSetKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
