<?php

require_once JPATH_PLATFORM.'/joomla/updater/adapters/extension.php';

/**
 * Test class for JUpdaterExtension.
 * Generated by PHPUnit on 2012-02-29 at 17:41:04.
 */
class JUpdaterExtensionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JUpdaterExtension
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JUpdaterExtension;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JUpdaterExtension::findUpdate
     * @todo Implement testFindUpdate().
     */
    public function testFindUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
