<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/user/helper.php';

/**
 * Test class for JUserHelper.
 * Generated by PHPUnit on 2012-02-29 at 17:40:50.
 */
class JUserHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JUserHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JUserHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JUserHelper::addUserToGroup
     * @todo Implement testAddUserToGroup().
     */
    public function testAddUserToGroup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUserHelper::getUserGroups
     * @todo Implement testGetUserGroups().
     */
    public function testGetUserGroups() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUserHelper::removeUserFromGroup
     * @todo Implement testRemoveUserFromGroup().
     */
    public function testRemoveUserFromGroup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUserHelper::setUserGroups
     * @todo Implement testSetUserGroups().
     */
    public function testSetUserGroups() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUserHelper::getProfile
     * @todo Implement testGetProfile().
     */
    public function testGetProfile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUserHelper::activateUser
     * @todo Implement testActivateUser().
     */
    public function testActivateUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUserHelper::getUserId
     * @todo Implement testGetUserId().
     */
    public function testGetUserId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUserHelper::getCryptedPassword
     * @todo Implement testGetCryptedPassword().
     */
    public function testGetCryptedPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUserHelper::getSalt
     * @todo Implement testGetSalt().
     */
    public function testGetSalt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JUserHelper::genRandomPassword
     * @todo Implement testGenRandomPassword().
     */
    public function testGenRandomPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
