<?php
/**
 * @package     Joomla.UnitTest
 * @subpackage  HTML
 *
 * @copyright   Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

require_once JPATH_PLATFORM.'/joomla/html/pane.php';

jimport('joomla.log.log');

/**
 * General inspector class for JPane.
 *
 * @package Joomla.UnitTest
 * @subpackage HTML
 * @since 11.3
 */
class JPaneInspector
{
	public $params = null;
	
	/**
	 * Constructor.
	 *
	 * @param   array  $params  Associative array of values
	 *
	 * @since   11.1
	 */
	function __construct($params = array())
	{
		$this->params = $params;
	}

	/**
	 * Creates a pane and creates the javascript object for it.
	 *
	 * @param   string  $id  The pane identifier.
	 *
	 * @return  string
	 *
	 * @since   11.1
	 *
	 * @deprecated    12.1
	 */
	public function startPane($id)
	{
		return 'startPane';
	}

	/**
	 * Ends the pane.
	 *
	 * @since   11.1
	 *
	 * @return  string
	 *
	 * @deprecated    12.1
	 */
	public function endPane()
	{
		return 'endPane';
	}

	/**
	 * Creates a panel with title text and starts that panel.
	 *
	 * @param   string  $text  The panel name and/or title.
	 * @param   string  $id    The panel identifer.
	 *
	 * @return  string
	 *
	 * @deprecated  12.1
	 * @since   11.1
	 */
	public function startPanel($text, $id)
	{
		return 'startPanel';
	}

	/**
	 * Ends a panel.
	 *
	 * @return  string
	 *
	 * @since   11.1
	 * @deprecated    12.1
	 */
	public function endPanel()
	{
		return 'endPanel';
	}

	/**
	 * Load the javascript behavior and attach it to the document.
	 *
	 * @return  void
	 *
	 * @deprecated    12.1
	 * @since   11.1
	 */
	protected function _loadBehavior()
	{
	}
}

/**
 * Test class for JPane.
 * Generated by PHPUnit on 2009-10-27 at 15:37:23.
 */
class JPaneTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Test JPane::getInstance().
	 */
	public function testGetInstance()
	{	
		$object = JPane::getInstance('Inspector', array('param' => 'test'));
		
		$this->assertInstanceOf(
			'JPaneInspector',
			$object
		);
		
		$this->assertThat(
			$object->params,
			$this->equalTo(array('param' => 'test'))
		);
	}
}