<?php

require_once JPATH_PLATFORM.'/joomla/database/query/mysql.php';

/**
 * Test class for JDatabaseQueryMysql.
 * Generated by PHPUnit on 2012-02-29 at 17:41:40.
 */
class JDatabaseQueryMysqlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDatabaseQueryMysql
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JDatabaseQueryMysql;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JDatabaseQueryMysql::processLimit
     * @todo Implement testProcessLimit().
     */
    public function testProcessLimit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQueryMysql::concatenate
     * @todo Implement testConcatenate().
     */
    public function testConcatenate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQueryMysql::setLimit
     * @todo Implement testSetLimit().
     */
    public function testSetLimit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
