<?php

require_once JPATH_PLATFORM.'/joomla/database/query/sqlsrv.php';

/**
 * Test class for JDatabaseQuerySqlsrv.
 * Generated by PHPUnit on 2012-02-29 at 17:41:40.
 */
class JDatabaseQuerySqlsrvTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDatabaseQuerySqlsrv
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JDatabaseQuerySqlsrv;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JDatabaseQuerySqlsrv::__toString
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQuerySqlsrv::castAsChar
     * @todo Implement testCastAsChar().
     */
    public function testCastAsChar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQuerySqlsrv::charLength
     * @todo Implement testCharLength().
     */
    public function testCharLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQuerySqlsrv::concatenate
     * @todo Implement testConcatenate().
     */
    public function testConcatenate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQuerySqlsrv::currentTimestamp
     * @todo Implement testCurrentTimestamp().
     */
    public function testCurrentTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQuerySqlsrv::length
     * @todo Implement testLength().
     */
    public function testLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
