<?php

require_once JPATH_PLATFORM.'/joomla/database/query/oracle.php';

/**
 * Test class for JDatabaseQueryOracle.
 * Generated by PHPUnit on 2012-02-29 at 17:41:39.
 */
class JDatabaseQueryOracleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JDatabaseQueryOracle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JDatabaseQueryOracle;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JDatabaseQueryOracle::bind
     * @todo Implement testBind().
     */
    public function testBind() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQueryOracle::getBounded
     * @todo Implement testGetBounded().
     */
    public function testGetBounded() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQueryOracle::clear
     * @todo Implement testClear().
     */
    public function testClear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQueryOracle::processLimit
     * @todo Implement testProcessLimit().
     */
    public function testProcessLimit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JDatabaseQueryOracle::setLimit
     * @todo Implement testSetLimit().
     */
    public function testSetLimit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
