<?php

require_once JPATH_PLATFORM.'/joomla/http/transport/curl.php';

/**
 * Test class for JHttpTransportCurl.
 * Generated by PHPUnit on 2012-02-29 at 17:41:21.
 */
class JHttpTransportCurlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JHttpTransportCurl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JHttpTransportCurl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JHttpTransportCurl::request
     * @todo Implement testRequest().
     */
    public function testRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JHttpTransportCurl::isSupported
     * @todo Implement testIsSupported().
     */
    public function testIsSupported() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
