<?php

require_once dirname(__FILE__) . '/../../../../libraries/joomla/utilities/xmlelement.php';

/**
 * Test class for JXMLElement.
 * Generated by PHPUnit on 2012-02-29 at 17:40:32.
 */
class JXMLElementTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JXMLElement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new JXMLElement;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JXMLElement::name
     * @todo Implement testName().
     */
    public function testName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JXMLElement::asFormattedXML
     * @todo Implement testAsFormattedXML().
     */
    public function testAsFormattedXML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
